# basic options
title: World Wildlife Protection Association
author: Muhammad
email: wildlife.protection@gmail.com
description: This organization works to protect many endangered animals. Snow Leapords, Mountain Gorillas, Black Rinos, and other endangered animals need our help.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
