# basic options
title: World Wildlife Protection Association
author: Muhammad
email: wildlife.protection@gmail.com
description: This organization works to protect many endangered animals. Snow Leapords, Mountain Gorillas, and Black Rinos need our help.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
